feat: adapt synth-parser to ontology changes
sdsc-ordes/cat-plus-zarr-converters pull request #9
Opened 2024-12-12 07:04 UTC by sabinem

This Pull Request:
- adapts the synth-parser to the ontology changes for the Synth data.

2025-01-17 13:57 UTC, cmdoret requested changes
Nice work! My general comment would be to try and group behaviour with data structures. Rather than accumulating functions in the graph builder, we could take advantage of rust type system to attach functionality directly to the structs and offload type-specific logic from the builder.

Other than that, it looks good and I only have a few minor suggestions :+1:

2025-01-17 13:57 UTC, cmdoret commented on synth-converter/src/graph/graph_builder.rs
> +                    .insert(subject, rdf::type_, cat::SetTemperatureAction)?;
**suggestion(non-blocking):** I think you could reduce redundancy here by using a `let match` statement:

```rust
let action_term = match action.action_name {
  ActionName::AddAction => cat::AddAction,
  ActionName::setPressureAction => cat::SetPressureAction,
  ...
};
self.graph.insert(subject, rdf::type_, action_term)?;
```

2025-01-17 13:57 UTC, cmdoret commented on synth-converter/src/graph/namespaces/unit.rs
> +// Rust cannot handle underscores in variable names, therefore this
```suggestion
// Rust cannot handle dashes in variable names, therefore this
```

2025-01-17 13:57 UTC, cmdoret commented on synth-converter/src/graph/namespaces/unit.rs
> +    }
**suggestion(non-blocking):** we could reuse a std trait such as `Display` (or `Into<String>` if you want to consume the `Unit`).

```rust
impl fmt::Display for Unit {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
      match self {
        Unit::Bar => "Bar",
        Unit::DegC => "DEG-C",
        Unit::MilliGM => "MilliGM",
        Unit::GMPerMilliL => "GM-PER-MilliL",
        Unit::MolPerL => "MOL-PER-L",
        Unit::RevPerMin => "REV-PER-MIN",
      }
    }
}
```

Then we can do things like `unit.to_string()`, `println!("{}", unit)` or `format!("{unit}")`

2025-01-20 14:00 UTC, sabinem commented
> My general comment would be to try and group behaviour with data structures. Rather than accumulating functions in the graph builder, we could take advantage of rust type system to attach functionality directly to the structs and offload type-specific logic from the builder.
> 
@cmdoret I get what you mean, but I have no idea how to go about this. Could you maybe make a suggestion. How about I take care of the small details and the we merge my work first and then you could make a PR on how to restructure this so that it gets to be more data driven?

2025-01-20 18:08 UTC, sabinem commented on synth-converter/src/graph/graph_builder.rs
> +        observation_unit: &NsTerm<'_>,
@cmdoret The unit is not always the same: it comes from the unit namespace, so all units there occur in some triples.

2025-01-20 18:17 UTC, sabinem commented
@cmdoret I followed up on your suggestions where it was easy for me to do so. I get your point of refactoring the code according to structs and implementing a `to_graph` trait for them. But to do this consistently would mean to refactor the code in a more substantial way. 

My suggestion here is the following: 
- let's merge the branch as it is.
- the code's functionality  is completely covered by integration tests (run `just test`)
- why don't you make a next PR suggesting to restructure the code as you propose and I will review your PR and try to learn from it.

So what do you think?

2025-01-21 07:33 UTC, sabinem commented on synth-converter/src/graph/graph_builder.rs
> +            .insert(&density_term, qudt::unit, Unit::GMPerMilliL.to_ns_term())?;
@cmdoret same as above: let's discuss a refactor of the graph builder code

2025-01-21 07:33 UTC, sabinem commented on synth-converter/src/graph/graph_builder.rs
> +    fn insert_an_error_margin(
@cmdoret same as above

2025-01-21 07:35 UTC, sabinem commented on synth-converter/src/graph/namespaces/unit.rs
> +    }
@cmdoret I struggled a bit to implement this and left it for now. Maybe we can look at this together when we do pair programming on the refactor?

2025-01-23 10:02 UTC, merged